#!/bin/sh

# This script typically modifies links or other files associated with foo,
# and/or removes files created by the package.

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#s6.1

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ## Below two methods to sniff for systemd being in use
        ## 1 = good
        ## 0 = bad
        ## these are /dev/null'd because if nothing matches then we have a bad return code and the install fails
        grep_systemd=$(sudo stat /proc/1/exe | grep -cim1 systemd) &> /dev/null
        pidof_systemd=$(pidof systemd && echo 1 || echo 0) &> /dev/null

        # Check if we have systemd
        if [ $grep_systemd -eq 1 ] || [ $pidof_systemd -eq 1 ]; then
            # TODO: should we check for [ hash systemctl 2> /dev/null ] first?

            # Check if we are actually uninstalling or just upgrading
            if [ $1 != upgrade ]; then
                # Disable the service
                systemctl disable pidee

                # Symlink pidee.service to /etc/systemd/system/pidee.service
                rm -f /etc/systemd/system/pidee.service

                exit 0
            fi

        # Or use System 5 init
        else
            # Check if we are actually uninstalling or just upgrading
            if [ $1 != upgrade ]; then

                # Remove from boot rc.d and silence errors (and stdout) if already installed
                update-rc.d -f pidee remove 2> /dev/null

                # Remove symlink /etc/init.d/pidee
                rm -f /etc/init.d/pidee

                exit 0
            fi
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
