#!/bin/sh

# This script typically completes any required configuration of the package foo 
# once foo has been unpacked from its Debian archive (".deb") file. 
#
# Often, 'postinst' scripts ask the user for input, and/or warn the user 
# that if he accepts default values, he should remember to go back and 
# re-configure that package as the situation warrants.
#
# Many 'postinst' scripts then execute any commands necessary to start or
# restart a service once a new package has been installed or upgraded.

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#s6.1

set -e

case "$1" in
    configure)
        
        # Add pidee user and group
        adduser --system --group --no-create-home --quiet pidee

        # Start service
        if [ -f /etc/init.d/pidee ];
        then
            service pidee start
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
