#!/bin/sh

# Add a pidee system user
# http://unix.stackexchange.com/questions/47880/how-debian-package-should-create-user-accounts
adduser --system --no-create-home --quiet pidee

# Start service
service pidee start
